### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ThomasJockin**
Final Review of spacing.

### CODE REVIEW

**Comment by impallari** [comment]
@davelab6 Should I be merging this? or better wait until it becomes more stable?

**Comment by davelab6** [comment]
Up to you guys but I think its not ready. Thomas and Alexei are you all
done?

**Comment by ThomasJockin** [comment]
Waiting for confirmation from Alexei on next steps.

**Comment by m4rc1e** [comment]
@ThomasJockin @alexeiva @davelab6 @impallari 

Ignore this pr for now. I'm currently doing some mastering on these files. @alexeiva did some improvements on Cyrillic etc. I will send a pr to @ThomasJockin because I forked from his repo, he'll then send one back to you.

Cheers,
Marc

**Comment by impallari** [comment]
Closing and ignoring this one, since there is a new one.

**Pull request closed without merging**
