### PR TITLE
fixes #6 percent

### LINKED ISSUE #6: Percent
Hey @alexeiva,

I also noticed the same problem in the percent.

old:
screen shot 2016-11-11 at 11 44 20

new:
screen shot 2016-11-11 at 11 44 14

I'm more than happy to revert this.

### PR DESCRIPTION
**Pull request by alexeiva**
before
screen shot 2016-11-10 at 1 33 46 pm

after
screen shot 2016-11-11 at 12 39 37 pm

cc @m4rc1e

### CODE REVIEW

**Comment by m4rc1e** [comment]
Thank you @alexeiva

**Comment by impallari** [comment]
@m4rc1e Do I safely merge this? or is there any conflict with the past pull requests?

**Comment by alexeiva** [comment]
this is safe to merge, as I have pulled from your repo prior to making these changes

**Comment by impallari** [comment]
Great!

**Pull request merged**
